### ISSUE TITLE
Deprecation warning for sphinx.util.compat.Directive

### ISSUE THREAD

**Issue by dhuang** [upsight/doctor#21]
Noticed this message:

```
/home/travis/build/dhuang/doctor/.tox/py27/lib/python2.7/site-packages/sphinx/util/compat.py:40: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use docutils' instead.
  RemovedInSphinx17Warning)
```

Just thought I'd bring it up because this will be an issue when Sphinx 1.7 is released since we require `sphinx >= 1.5.4, < 2.0.0`. Switch to `docutils.parsers.rst.Directive` instead (or switch to `< 1.7.0`).

**Comment by boralyl** [comment]
No longer an issue.
