### ISSUE TITLE
Auto generated documentation doesn't work on GET endpoints that contain arrays of strings

### ISSUE THREAD

**Issue by boralyl** [upsight/doctor#27]
If a GET endpoint has a query string parameter that is an array of strings, the auto generated documentation fails with (parameter is names in this case): `"names must be a valid type (array)"`

When I parse the query string parameters names looks like this:  

```python
{'names': "['example name']"}
```

The problem is that the above value isn't something that can be json loaded.  If the single quotes inside the list were double quotes it would work as expected.

When generating documentation, doctor should handle this case properly.

**Comment by noonat** [comment]
It seems like the code making requests for the documentation isn't JSON dumping it, and it's instead being coerced to a Python string.
