### ISSUE TITLE
doctor attempts to document non doctor type params and fails

### ISSUE THREAD

**Issue by boralyl** [upsight/doctor#70]
When generating documentation if a parameter is passed to a logic function (say from a decorator) and it is not a doctor type, docs generation fails.

```
Exception occurred:
  File "/home/user/.virtualenvs/my-api/lib/python3.6/site-packages/doctor/docs/base.py", line 150, in get_json_object_lines
    types = [str(annotated_type.native_type.__name__)]
AttributeError: type object 'User' has no attribute 'native_type'
```

**Comment by noonat** [comment]
I guess this is a useful benefit of all the types coming from `SuperType`, as it should allow us to do an `issubclass` check on the type, I think?

**Comment by boralyl** [comment]
I think we need to do issubclass, but yes that should work.
