### ISSUE TITLE
Include JSON body in parse error message

### ISSUE THREAD

**Issue by pkar** [upsight/doctor#98]
Right now it just gives the JSON error but no context as to what was input here https://github.com/upsight/doctor/blob/master/doctor/parsers.py#L160

So you end up with just a generic error like 

```
Error parsing JSON: Expecting value: line 1 column 1 (char 0)
```

Would be nice to have the body in the message

```
message = 'Error parsing JSON: %r error: %s' % (value, e)
```

**Comment by boralyl** [comment]
Fixed in #101
